import HeaderCounted from "@/components/HeaderCounted";
import Head from "next/head";
import { Col, Container, Row, Accordion } from "react-bootstrap";

const Webentwicklung = ({ city }) => {
	const formattedCity = city.charAt(0).toUpperCase() + city.slice(1);

	return (
		<div className="mt-5 pt-2">
			<HeaderCounted />
			<Container className="mt-5 text-black">
				<Head>
					<title>{`Pixel Genie - Professionelle Webseiten Erstellung, SEO, Webdesign in ${formattedCity}`}</title>
					<meta
						name="description"
						content={`Pixel Genie in ${formattedCity}: Ihr Partner für Webentwicklung, Webdesign, SEO und Online-Marketing. Wir erstellen maßgeschneiderte Webseiten und bieten umfassende digitale Lösungen.`}
					/>
					<meta name="robots" content="index, follow" />
				</Head>

				<Row className="mt-5">
					<Col className="mt-5 pt-5 bg-white rounded">
						<h1 className="text-center text-bold shadow-lg rounded">{`Pixel Genie - Professionelle Webseiten-Erstellung und Webentwicklung in ${formattedCity}`}</h1>
						<p>
							{`Pixel Genie ist Ihre erste Wahl für moderne und leistungsfähige Webseiten in ${formattedCity}. Mit einem erfahrenen Team aus Experten für Webentwicklung, Webdesign und SEO erstellen wir maßgeschneiderte Webseiten, die nicht nur gut aussehen, sondern auch funktional und benutzerfreundlich sind. Unsere Websites sind perfekt optimiert für Suchmaschinen (SEO), um Ihr Unternehmen online sichtbar zu machen.`}
						</p>

						<p>
							{`Unser Fokus liegt auf der Erstellung von Webseiten, die sich durch hervorragende Benutzerfreundlichkeit (UX) und ansprechendes Design (UI) auszeichnen. Egal, ob Sie eine einfache Unternehmensseite oder eine komplexe Webanwendung benötigen – bei Pixel Genie in ${formattedCity} erhalten Sie maßgeschneiderte Lösungen, die genau auf Ihre Bedürfnisse zugeschnitten sind.`}
						</p>

						<h2 className="mt-4 text-center text-bold">{`SEO und Online-Marketing in ${formattedCity}`}</h2>
						<p>
							{`Eine erfolgreiche Webseite benötigt mehr als nur ein ansprechendes Design. Bei Pixel Genie verstehen wir, dass SEO (Suchmaschinenoptimierung) ein integraler Bestandteil jeder erfolgreichen Online-Strategie ist. Wir integrieren von Anfang an alle wichtigen SEO-Praktiken in den Entwicklungsprozess, um sicherzustellen, dass Ihre Webseite in den Suchergebnissen von Google und anderen Suchmaschinen weit oben erscheint.`}
						</p>

						<p>
							{`Unsere Dienstleistungen im Bereich Online-Marketing gehen weit über die reine Webseiten-Erstellung hinaus. Wir unterstützen Sie auch bei der Entwicklung von Content-Strategien, Social Media Marketing und der Analyse Ihrer Webseiten-Performance. Unsere ganzheitliche Herangehensweise garantiert, dass Ihre Webseite nicht nur Besucher anzieht, sondern auch Conversions generiert.`}
						</p>

						<h2 className="mt-4 text-center text-bold">{`Webentwicklung und Designlösungen`}</h2>
						<p>
							{`Unser Team in ${formattedCity} verwendet die neuesten Technologien und Frameworks wie React, Next.js und Node.js, um sicherzustellen, dass Ihre Webseite blitzschnell lädt und auf allen Geräten perfekt funktioniert. Responsive Design steht dabei immer im Vordergrund – Ihre Webseite wird auf Smartphones, Tablets und Desktop-Computern gleichermaßen beeindrucken.`}
						</p>

						<p>
							{`Durch unsere maßgeschneiderte Webentwicklung und unser fundiertes Fachwissen im Bereich UX/UI Design bieten wir eine ganzheitliche Lösung, die auf die besonderen Anforderungen Ihres Unternehmens zugeschnitten ist. Wir legen großen Wert darauf, dass jede Webseite, die wir erstellen, nicht nur ästhetisch ansprechend, sondern auch funktional und leicht zu bedienen ist.`}
						</p>

						<h2 className="mt-4 text-center text-bold">{`Unsere Dienstleistungen im Überblick`}</h2>
						<ul className="text-center">
							<h5>{`Professionelle Webseiten-Erstellung und Webdesign`}</h5>
							<h5>{`Individuelle Webentwicklung mit React, Next.js und mehr`}</h5>
							<h5>{`SEO-Optimierung für bessere Suchmaschinenplatzierungen`}</h5>
							<h5>{`Online-Marketing: Content-Strategien, Social Media, und mehr`}</h5>
							<h5>{`UX/UI Design für benutzerfreundliche und moderne Webseiten`}</h5>
							<h5>{`Wartung und Support nach dem Launch Ihrer Webseite`}</h5>
						</ul>

						<p>
							{`Wenn Sie auf der Suche nach einem zuverlässigen Partner für die Erstellung Ihrer Webseite oder die Optimierung Ihrer Online-Präsenz in ${formattedCity} sind, dann ist Pixel Genie die richtige Wahl. Unser Team aus erfahrenen Entwicklern, Designern und SEO-Experten steht Ihnen zur Seite, um Ihr digitales Projekt von der Planung bis zur Umsetzung erfolgreich zu gestalten.`}
						</p>
					</Col>
				</Row>

				<Row className="my-5 shadow-lg rounded">
					<h2 className="text-center my-2 text-bold bg-white rounded">{`Häufig gestellte Fragen zu Webentwicklung und Webseiten-Erstellung in ${formattedCity}`}</h2>
					<Col>
						<Accordion className="my-3">
							<Accordion.Item eventKey="0">
								<Accordion.Header>
									<span>{`Warum sollte ich Pixel Genie für die Erstellung meiner Webseite wählen?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Pixel Genie bietet in ${formattedCity} umfassende Dienstleistungen in den Bereichen Webentwicklung, Webdesign und SEO. Wir erstellen maßgeschneiderte Webseiten, die sowohl technisch ausgereift als auch optisch ansprechend sind. Unsere langjährige Erfahrung und unser Know-how im Online-Marketing machen uns zu einem idealen Partner für Ihr Webprojekt.`}
								</Accordion.Body>
							</Accordion.Item>

							<Accordion.Item eventKey="1">
								<Accordion.Header>
									<span>{`Welche Technologien nutzt Pixel Genie für die Webentwicklung?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Wir arbeiten mit modernsten Technologien wie React, Next.js und Node.js, um hochleistungsfähige und skalierbare Webseiten zu erstellen. Diese Technologien gewährleisten, dass Ihre Webseite schnell, sicher und zukunftssicher ist.`}
								</Accordion.Body>
							</Accordion.Item>

							<Accordion.Item eventKey="2">
								<Accordion.Header>
									<span>{`Bietet Pixel Genie auch SEO-Optimierung an?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Ja, SEO ist ein wesentlicher Bestandteil unserer Dienstleistungen. Wir optimieren Ihre Webseite von Anfang an, damit sie in den Suchmaschinen gut platziert wird und die Sichtbarkeit Ihres Unternehmens erhöht. Dies umfasst sowohl On-Page- als auch Off-Page-Optimierung.`}
								</Accordion.Body>
							</Accordion.Item>

							<Accordion.Item eventKey="3">
								<Accordion.Header>
									<span>{`Wie lange dauert es, eine Webseite zu erstellen?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Die Dauer hängt von der Komplexität des Projekts ab. Eine einfache Webseite kann innerhalb weniger Wochen erstellt werden, während umfangreichere Projekte mehrere Monate in Anspruch nehmen können. Wir arbeiten eng mit Ihnen zusammen, um den Zeitrahmen realistisch zu planen.`}
								</Accordion.Body>
							</Accordion.Item>

							<Accordion.Item eventKey="4">
								<Accordion.Header>
									<span>{`Kann ich meine Webseite nach der Fertigstellung selbst verwalten?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Ja, wir bieten Ihnen benutzerfreundliche Content-Management-Lösungen (CMS), wie zum Beispiel WordPress, mit denen Sie Ihre Webseite nach der Fertigstellung selbst verwalten und aktualisieren können. Bei Bedarf bieten wir auch Schulungen und Support an.`}
								</Accordion.Body>
							</Accordion.Item>

							<Accordion.Item eventKey="5">
								<Accordion.Header>
									<span>{`Welche Kosten sind mit der Erstellung einer Webseite verbunden?`}</span>
								</Accordion.Header>
								<Accordion.Body>
									{`Die Kosten für die Erstellung einer Webseite hängen von verschiedenen Faktoren ab, wie dem Funktionsumfang, Design und den individuellen Anforderungen. Wir erstellen für jeden Kunden ein maßgeschneidertes Angebot, das auf den spezifischen Bedürfnissen und Zielen basiert.`}
								</Accordion.Body>
							</Accordion.Item>
						</Accordion>
					</Col>
				</Row>
			</Container>
		</div>
	);
};

export async function getStaticPaths() {
	// Definiere die Städte, die statisch verarbeitet werden sollen
	const paths = [
		{ params: { city: "berlin" } },
		{ params: { city: "muenchen" } },
		{ params: { city: "hamburg" } },
		{ params: { city: "frankfurt" } },
		{ params: { city: "stuttgart" } },
		{ params: { city: "duesseldorf" } },
		{ params: { city: "leipzig" } },
		{ params: { city: "naumburg" } },
		{ params: { city: "olpe" } },
		{ params: { city: "selm" } },
		{ params: { city: "schleswig" } },
		{ params: { city: "menden" } },
		{ params: { city: "potsdam" } },
		{ params: { city: "lahr" } },
		{ params: { city: "senden" } },
		{ params: { city: "lingen" } },
		{ params: { city: "paderborn" } },
		{ params: { city: "bamberg" } },
		{ params: { city: "pforzheim" } },
		{ params: { city: "langenhagen" } },
		{ params: { city: "braunschweig" } },
		{ params: { city: "versmold" } },
		{ params: { city: "berlin-wilmersdorf" } },
		{ params: { city: "esslingen-am-neckar" } },
		{ params: { city: "geldern" } },
		{ params: { city: "moenchengladbach" } },
		{ params: { city: "bad-salzungen" } },
		{ params: { city: "erkelenz" } },
		{ params: { city: "bad-kreuznach" } },
		{ params: { city: "hamburg-mitte" } },
		{ params: { city: "nettetal" } },
		{ params: { city: "dreieich" } },
		{ params: { city: "lengerich" } },
		{ params: { city: "duisburg" } },
		{ params: { city: "zuelpich" } },
		{ params: { city: "hildesheim" } },
		{ params: { city: "bad-homburg-vor-der-hoehe" } },
		{ params: { city: "goettingen" } },
		{ params: { city: "metzingen" } },
		{ params: { city: "goeppingen" } },
		{ params: { city: "eschborn" } },
		{ params: { city: "beckum" } },
		{ params: { city: "buchholz-in-der-nordheide" } },
		{ params: { city: "waren" } },
		{ params: { city: "schloss-holte-stukenbrock" } },
		{ params: { city: "weinheim" } },
		{ params: { city: "soltau" } },
		{ params: { city: "bruehl" } },
		{ params: { city: "sangerhausen" } },
		{ params: { city: "leonberg" } },
		{ params: { city: "burg" } },
		{ params: { city: "eberswalde" } },
		{ params: { city: "strausberg" } },
		{ params: { city: "weyhe" } },
		{ params: { city: "nordenham" } },
		{ params: { city: "heppenheim" } },
		{ params: { city: "kelkheim" } },
		{ params: { city: "osterholz-scharmbeck" } },
		{ params: { city: "dueren" } },
		{ params: { city: "freudenstadt" } },
		{ params: { city: "reichenbach-im-vogtland" } },
		{ params: { city: "geilenkirchen" } },
		{ params: { city: "koeln-marienburg" } },
		{ params: { city: "bedburg" } },
		{ params: { city: "schmallenberg" } },
		{ params: { city: "deggendorf" } },
		{ params: { city: "emmerich-am-rhein" } },
		{ params: { city: "hockenheim" } },
		{ params: { city: "kreuztal" } },
		{ params: { city: "dingolfing" } },
		{ params: { city: "garmisch-partenkirchen" } },
		{ params: { city: "offenbach-am-main" } },
		{ params: { city: "reinbek" } },
		{ params: { city: "lutherstadt-eisleben" } },
		{ params: { city: "mettmann" } },
		{ params: { city: "wipperfuerth" } },
		{ params: { city: "vechta" } },
		{ params: { city: "hattersheim-am-main" } },
		{ params: { city: "frankenthal" } },
		{ params: { city: "vaihingen-an-der-enz" } },
		{ params: { city: "schweinfurt" } },
		{ params: { city: "aalen" } },
		{ params: { city: "greiz" } },
		{ params: { city: "castrop-rauxel" } },
		{ params: { city: "lauf-an-der-pegnitz" } },
		{ params: { city: "gera" } },
		{ params: { city: "waiblingen" } },
		{ params: { city: "hennigsdorf" } },
		{ params: { city: "calw" } },
		{ params: { city: "freital" } },
		{ params: { city: "eppingen" } },
		{ params: { city: "schwabach" } },
		{ params: { city: "uetze" } },
		{ params: { city: "hamburg-eimsbuettel" } },
		{ params: { city: "muenchen-harlaching" } },
		{ params: { city: "bad-mergentheim" } },
		{ params: { city: "oldenburg" } },
		{ params: { city: "andernach" } },
		{ params: { city: "kempten" } },
		{ params: { city: "gevelsberg" } },
		{ params: { city: "solingen" } },
		{ params: { city: "pfaffenhofen-an-der-ilm" } },
		{ params: { city: "neustadt-an-der-weinstrasse" } },
		{ params: { city: "muehlheim-am-main" } },
		{ params: { city: "bad-rappenau" } },
		{ params: { city: "neu-ulm" } },
		{ params: { city: "salzkotten" } },
		{ params: { city: "rees" } },
		{ params: { city: "kiel" } },
		{ params: { city: "bretten" } },
		{ params: { city: "leimen" } },
		{ params: { city: "georgsmarienhuette" } },
		{ params: { city: "bernau-bei-berlin" } },
		{ params: { city: "trier" } },
		{ params: { city: "noerdlingen" } },
		{ params: { city: "roth" } },
		{ params: { city: "isernhagen" } },
		{ params: { city: "juelich" } },
		{ params: { city: "seevetal" } },
		{ params: { city: "sinsheim" } },
		{ params: { city: "merseburg" } },
		{ params: { city: "moerfelden-walldorf" } },
		{ params: { city: "juechen" } },
		{ params: { city: "velbert" } },
		{ params: { city: "petershagen" } },
		{ params: { city: "oer-erkenschwick" } },
		{ params: { city: "blieskastel" } },
		{ params: { city: "walsrode" } },
		{ params: { city: "hofheim-am-taunus" } },
		{ params: { city: "voerde" } },
		{ params: { city: "kronberg-im-taunus" } },
		{ params: { city: "sprockhoevel" } },
		{ params: { city: "friedrichshafen" } },
		{ params: { city: "bornheim" } },
		{ params: { city: "bad-oeynhausen" } },
		{ params: { city: "delbrueck" } },
		{ params: { city: "wittmund" } },
		{ params: { city: "hohen-neuendorf" } },
		{ params: { city: "buedingen" } },
		{ params: { city: "wildeshausen" } },
		{ params: { city: "wachtberg" } },
		{ params: { city: "plettenberg" } },
		{ params: { city: "hassloch" } },
		{ params: { city: "leichlingen" } },
		{ params: { city: "berlin-grunewald" } },
		{ params: { city: "geislingen-an-der-steige" } },
		{ params: { city: "coswig" } },
		{ params: { city: "worms" } },
		{ params: { city: "emsdetten" } },
		{ params: { city: "erding" } },
		{ params: { city: "koblenz" } },
		{ params: { city: "remscheid" } },
		{ params: { city: "oberhausen" } },
		{ params: { city: "teltow" } },
		{ params: { city: "muenchen-schwabing" } },
		{ params: { city: "bensheim" } },
		{ params: { city: "radolfzell-am-bodensee" } },
		{ params: { city: "lohne-oldenburg" } },
		{ params: { city: "plauen" } },
		{ params: { city: "gifhorn" } },
		{ params: { city: "forchheim" } },
		{ params: { city: "lichtenfels" } },
		{ params: { city: "gelnhausen" } },
		{ params: { city: "weiterstadt" } },
		{ params: { city: "schwandorf" } },
		{ params: { city: "kempen" } },
		{ params: { city: "wunstorf" } },
		{ params: { city: "lemgo" } },
		{ params: { city: "celle" } },
		{ params: { city: "koeln-lindenthal" } },
		{ params: { city: "eislingen" } },
		{ params: { city: "falkensee" } },
		{ params: { city: "stuhr" } },
		{ params: { city: "dorsten" } },
		{ params: { city: "rheinberg" } },
		{ params: { city: "albstadt" } },
		{ params: { city: "nuernberg" } },
		{ params: { city: "krefeld" } },
		{ params: { city: "geseke" } },
		{ params: { city: "northeim" } },
		{ params: { city: "wangen-im-allgaeu" } },
		{ params: { city: "wiesloch" } },
		{ params: { city: "bad-vilbel" } },
		{ params: { city: "alfter" } },
		{ params: { city: "kleve" } },
		{ params: { city: "st-wendel" } },
		{ params: { city: "winnenden" } },
		{ params: { city: "luedenscheid" } },
		{ params: { city: "heilbronn" } },
		{ params: { city: "elmshorn" } },
		{ params: { city: "koeln-muelheim" } },
		{ params: { city: "muehldorf-am-inn" } },
		{ params: { city: "kaarst" } },
		{ params: { city: "neckarsulm" } },
		{ params: { city: "bad-nauheim" } },
		{ params: { city: "augsburg" } },
		{ params: { city: "singen" } },
		{ params: { city: "wedemark" } },
		{ params: { city: "hoyerswerda" } },
		{ params: { city: "werdau" } },
		{ params: { city: "kassel" } },
		{ params: { city: "kevelaer" } },
		{ params: { city: "neukirchen-vluyn" } },
		{ params: { city: "eisenhuettenstadt" } },
		{ params: { city: "idar-oberstein" } },
		{ params: { city: "geesthacht" } },
		{ params: { city: "delitzsch" } },
		{ params: { city: "lindau-bodensee" } },
		{ params: { city: "hennef" } },
		{ params: { city: "barsinghausen" } },
		{ params: { city: "goslar" } },
		{ params: { city: "neubrandenburg" } },
		{ params: { city: "wiesbaden" } },
		{ params: { city: "baden-baden" } },
		{ params: { city: "heidelberg" } },
		{ params: { city: "dessau-rosslau" } },
		{ params: { city: "baunatal" } },
		{ params: { city: "edewecht" } },
		{ params: { city: "merzig" } },
		{ params: { city: "riesa" } },
		{ params: { city: "schwelm" } },
		{ params: { city: "brandenburg-an-der-havel" } },
		{ params: { city: "sankt-augustin" } },
		{ params: { city: "bautzen" } },
		{ params: { city: "goch" } },
		{ params: { city: "gauting" } },
		{ params: { city: "meerbusch" } },
		{ params: { city: "ahlen" } },
		{ params: { city: "haar" } },
		{ params: { city: "flensburg" } },
		{ params: { city: "obertshausen" } },
		{ params: { city: "reutlingen" } },
		{ params: { city: "ingolstadt" } },
		{ params: { city: "neufahrn-bei-freising" } },
		{ params: { city: "ulm" } },
		{ params: { city: "meissen" } },
		{ params: { city: "neu-wulmstorf" } },
		{ params: { city: "wilhelmshaven" } },
		{ params: { city: "ostfildern" } },
		{ params: { city: "willich" } },
		{ params: { city: "regensburg" } },
		{ params: { city: "erftstadt" } },
		{ params: { city: "loerrach" } },
		{ params: { city: "mainz" } },
		{ params: { city: "helmstedt" } },
		{ params: { city: "puchheim" } },
		{ params: { city: "lampertheim" } },
		{ params: { city: "dortmund" } },
		{ params: { city: "bonn" } },
		{ params: { city: "goerlitz" } },
		{ params: { city: "stadtlohn" } },
		{ params: { city: "olching" } },
		{ params: { city: "aurich" } },
		{ params: { city: "loehne" } },
		{ params: { city: "oberursel" } },
		{ params: { city: "dresden" } },
		{ params: { city: "neumarkt-in-der-oberpfalz" } },
		{ params: { city: "herten" } },
		{ params: { city: "hameln" } },
		{ params: { city: "papenburg" } },
		{ params: { city: "muehlhausen-(thueringen)" } },
		{ params: { city: "stolberg" } },
		{ params: { city: "ahaus" } },
		{ params: { city: "bruchkoebel" } },
		{ params: { city: "minden" } },
		{ params: { city: "eschweiler" } },
		{ params: { city: "dachau" } },
		{ params: { city: "wesel" } },
		{ params: { city: "gummersbach" } },
		{ params: { city: "weil-am-rhein" } },
		{ params: { city: "bad-krozingen" } },
		{ params: { city: "muenster" } },
		{ params: { city: "donaueschingen" } },
		{ params: { city: "siegen" } },
		{ params: { city: "berlin-mitte" } },
		{ params: { city: "chemnitz" } },
		{ params: { city: "mosbach" } },
		{ params: { city: "achim" } },
		{ params: { city: "werl" } },
		{ params: { city: "schorndorf" } },
		{ params: { city: "rheinfelden" } },
		{ params: { city: "gross-umstadt" } },
		{ params: { city: "muehlacker" } },
		{ params: { city: "neustadt-am-ruebenberge" } },
		{ params: { city: "erkrath" } },
		{ params: { city: "senftenberg" } },
		{ params: { city: "schortens" } },
		{ params: { city: "fulda" } },
		{ params: { city: "memmingen" } },
		{ params: { city: "enger" } },
		{ params: { city: "nienburg" } },
		{ params: { city: "dillenburg" } },
		{ params: { city: "mannheim" } },
		{ params: { city: "stendal" } },
		{ params: { city: "meckenheim" } },
		{ params: { city: "ettlingen" } },
		{ params: { city: "wolfenbuettel" } },
		{ params: { city: "dietzenbach" } },
		{ params: { city: "ingelheim-am-rhein" } },
		{ params: { city: "grevenbroich" } },
		{ params: { city: "duelmen" } },
		{ params: { city: "remseck-am-neckar" } },
		{ params: { city: "niederkassel" } },
		{ params: { city: "giessen" } },
		{ params: { city: "geestland" } },
		{ params: { city: "siegburg" } },
		{ params: { city: "limbach-oberfrohna" } },
		{ params: { city: "haren" } },
		{ params: { city: "weissenfels" } },
		{ params: { city: "leverkusen" } },
		{ params: { city: "wolfsburg" } },
		{ params: { city: "frankfurt-am-main" } },
		{ params: { city: "haltern-am-see" } },
		{ params: { city: "langenfeld" } },
		{ params: { city: "leinfelden-echterdingen" } },
		{ params: { city: "bad-waldsee" } },
		{ params: { city: "vreden" } },
		{ params: { city: "ilsede" } },
		{ params: { city: "stralsund" } },
		{ params: { city: "passau" } },
		{ params: { city: "werder-(havel)" } },
		{ params: { city: "berlin-friedrichshain" } },
		{ params: { city: "hagen" } },
		{ params: { city: "itzehoe" } },
		{ params: { city: "berlin-dahlem" } },
		{ params: { city: "weiden-in-der-oberpfalz" } },
		{ params: { city: "sundern" } },
		{ params: { city: "ennepetal" } },
		{ params: { city: "rheinbach" } },
		{ params: { city: "emmendingen" } },
		{ params: { city: "kaufbeuren" } },
		{ params: { city: "buxtehude" } },
		{ params: { city: "gruenwald" } },
		{ params: { city: "koethen" } },
		{ params: { city: "schramberg" } },
		{ params: { city: "bueren" } },
		{ params: { city: "unna" } },
		{ params: { city: "kulmbach" } },
		{ params: { city: "wuerzburg" } },
		{ params: { city: "bernburg" } },
		{ params: { city: "waltrop" } },
		{ params: { city: "idstein" } },
		{ params: { city: "sonneberg" } },
		{ params: { city: "freiburg-im-breisgau" } },
		{ params: { city: "rottenburg-am-neckar" } },
		{ params: { city: "froendenberg" } },
		{ params: { city: "pirna" } },
		{ params: { city: "panketal" } },
		{ params: { city: "roesrath" } },
		{ params: { city: "oranienburg" } },
		{ params: { city: "weinstadt" } },
		{ params: { city: "balingen" } },
		{ params: { city: "ellwangen" } },
		{ params: { city: "duderstadt" } },
		{ params: { city: "waldkirch" } },
		{ params: { city: "ilmenau" } },
		{ params: { city: "berlin-schoeneberg" } },
		{ params: { city: "schwedt" } },
		{ params: { city: "aschersleben" } },
		{ params: { city: "rheda-wiedenbrueck" } },
		{ params: { city: "ravensburg" } },
		{ params: { city: "einbeck" } },
		{ params: { city: "achern" } },
		{ params: { city: "ahrensburg" } },
		{ params: { city: "rostock" } },
		{ params: { city: "friedberg-(bayern)" } },
		{ params: { city: "warstein" } },
		{ params: { city: "tuttlingen" } },
		{ params: { city: "kaltenkirchen" } },
		{ params: { city: "stadtallendorf" } },
		{ params: { city: "uelzen" } },
		{ params: { city: "overath" } },
		{ params: { city: "salzgitter" } },
		{ params: { city: "guenzburg" } },
		{ params: { city: "werne" } },
		{ params: { city: "garbsen" } },
		{ params: { city: "landshut" } },
		{ params: { city: "unterhaching" } },
		{ params: { city: "schwerin" } },
		{ params: { city: "stassfurt" } },
		{ params: { city: "kitzingen" } },
		{ params: { city: "laupheim" } },
		{ params: { city: "ibbenbueren" } },
		{ params: { city: "hoerstel" } },
		{ params: { city: "landsberg-am-lech" } },
		{ params: { city: "halberstadt" } },
		{ params: { city: "villingen-schwenningen" } },
		{ params: { city: "gross-gerau" } },
		{ params: { city: "seelze" } },
		{ params: { city: "bramsche" } },
		{ params: { city: "lehrte" } },
		{ params: { city: "guetersloh" } },
		{ params: { city: "detmold" } },
		{ params: { city: "doebeln" } },
		{ params: { city: "traunreut" } },
		{ params: { city: "leutkirch-im-allgaeu" } },
		{ params: { city: "floersheim-am-main" } },
		{ params: { city: "sonthofen" } },
		{ params: { city: "geretsried" } },
		{ params: { city: "offenburg" } },
		{ params: { city: "rottach-egern" } },
		{ params: { city: "magdeburg" } },
		{ params: { city: "bruchsal" } },
		{ params: { city: "bottrop" } },
		{ params: { city: "amberg" } },
		{ params: { city: "darmstadt" } },
		{ params: { city: "rheine" } },
		{ params: { city: "aichach" } },
		{ params: { city: "heide" } },
		{ params: { city: "peine" } },
		{ params: { city: "varel" } },
		{ params: { city: "neusaess" } },
		{ params: { city: "langen" } },
		{ params: { city: "ueberlingen" } },
		{ params: { city: "muenchen-pasing" } },
		{ params: { city: "ganderkesee" } },
		{ params: { city: "wuelfrath" } },
		{ params: { city: "fuerth" } },
		{ params: { city: "greven" } },
		{ params: { city: "zwickau" } },
		{ params: { city: "ehingen" } },
		{ params: { city: "datteln" } },
		{ params: { city: "leer" } },
		{ params: { city: "bad-neuenahr-ahrweiler" } },
		{ params: { city: "heinsberg" } },
		{ params: { city: "senden-nrw" } },
		{ params: { city: "rendsburg" } },
		{ params: { city: "hattingen" } },
		{ params: { city: "frankfurt-flughafen" } },
		{ params: { city: "lage" } },
		{ params: { city: "friedberg-hessen" } },
		{ params: { city: "mechernich" } },
		{ params: { city: "koenigs-wusterhausen" } },
		{ params: { city: "wuerselen" } },
		{ params: { city: "gelsenkirchen" } },
		{ params: { city: "voelklingen" } },
		{ params: { city: "hamm" } },
		{ params: { city: "friesoythe" } },
		{ params: { city: "waldkraiburg" } },
		{ params: { city: "berlin-charlottenburg" } },
		{ params: { city: "nidderau" } },
		{ params: { city: "apolda" } },
		{ params: { city: "kornwestheim" } },
		{ params: { city: "rotenburg-wuemme" } },
		{ params: { city: "lippstadt" } },
		{ params: { city: "karlsfeld" } },
		{ params: { city: "crailsheim" } },
		{ params: { city: "hannover" } },
		{ params: { city: "freiberg" } },
		{ params: { city: "husum" } },
		{ params: { city: "sankt-ingbert" } },
		{ params: { city: "hamburg-wandsbek" } },
		{ params: { city: "konstanz" } },
		{ params: { city: "waldshut-tiengen" } },
		{ params: { city: "cloppenburg" } },
		{ params: { city: "zweibruecken" } },
		{ params: { city: "porta-westfalica" } },
		{ params: { city: "meschede" } },
		{ params: { city: "senden-(bayern)" } },
		{ params: { city: "backnang" } },
		{ params: { city: "suhl" } },
		{ params: { city: "radebeul" } },
		{ params: { city: "dinslaken" } },
		{ params: { city: "berlin-zehlendorf" } },
		{ params: { city: "pulheim" } },
		{ params: { city: "sondershausen" } },
		{ params: { city: "pullach-im-isartal" } },
		{ params: { city: "rottweil" } },
		{ params: { city: "roedermark" } },
		{ params: { city: "netphen" } },
		{ params: { city: "luenen" } },
		{ params: { city: "kaiserslautern" } },
		{ params: { city: "coesfeld" } },
		{ params: { city: "blankenfelde-mahlow" } },
		{ params: { city: "bad-oldesloe" } },
		{ params: { city: "harsewinkel" } },
		{ params: { city: "bremen" } },
		{ params: { city: "rudolstadt" } },
		{ params: { city: "neumuenster" } },
		{ params: { city: "meiningen" } },
		{ params: { city: "ludwigsfelde" } },
		{ params: { city: "zerbst" } },
		{ params: { city: "huerth" } },
		{ params: { city: "bad-hersfeld" } },
		{ params: { city: "luckenwalde" } },
		{ params: { city: "marburg" } },
		{ params: { city: "sindelfingen" } },
		{ params: { city: "gardelegen" } },
		{ params: { city: "moormerland" } },
		{ params: { city: "bad-harzburg" } },
		{ params: { city: "norderstedt" } },
		{ params: { city: "korbach" } },
		{ params: { city: "sehnde" } },
		{ params: { city: "ruesselsheim-am-main" } },
		{ params: { city: "ottobrunn" } },
		{ params: { city: "karlsruhe" } },
		{ params: { city: "weilheim-in-oberbayern" } },
		{ params: { city: "unterschleissheim" } },
		{ params: { city: "freising" } },
		{ params: { city: "heidenheim-an-der-brenz" } },
		{ params: { city: "melle" } },
		{ params: { city: "lutherstadt-wittenberg" } },
		{ params: { city: "ratingen" } },
		{ params: { city: "bad-honnef" } },
		{ params: { city: "moessingen" } },
		{ params: { city: "rodgau" } },
		{ params: { city: "speyer" } },
		{ params: { city: "kehl" } },
		{ params: { city: "frankfurt-oder" } },
		{ params: { city: "pinneberg" } },
		{ params: { city: "riedstadt" } },
		{ params: { city: "buehl" } },
		{ params: { city: "oelde" } },
		{ params: { city: "herne" } },
		{ params: { city: "eckernfoerde" } },
		{ params: { city: "neustrelitz" } },
		{ params: { city: "meinerzhagen" } },
		{ params: { city: "bitterfeld-wolfen" } },
		{ params: { city: "rheinstetten" } },
		{ params: { city: "viernheim" } },
		{ params: { city: "leinefelde-worbis" } },
		{ params: { city: "bad-soden-am-taunus" } },
		{ params: { city: "springe" } },
		{ params: { city: "wuppertal" } },
		{ params: { city: "muenchen-maxvorstadt" } },
		{ params: { city: "syke" } },
		{ params: { city: "attendorn" } },
		{ params: { city: "schwanewede" } },
		{ params: { city: "buende" } },
		{ params: { city: "saarbruecken" } },
		{ params: { city: "rastede" } },
		{ params: { city: "wetzlar" } },
		{ params: { city: "wedel" } },
		{ params: { city: "steinhagen" } },
		{ params: { city: "nuertingen" } },
		{ params: { city: "verden" } },
		{ params: { city: "salzwedel" } },
		{ params: { city: "neuwied" } },
		{ params: { city: "rietberg" } },
		{ params: { city: "erbach" } },
		{ params: { city: "bad-salzuflen" } },
		{ params: { city: "koenigswinter" } },
		{ params: { city: "hann-muenden" } },
		{ params: { city: "lindlar" } },
		{ params: { city: "luebbecke" } },
		{ params: { city: "bad-zwischenahn" } },
		{ params: { city: "bremerhaven" } },
		{ params: { city: "altenburg" } },
		{ params: { city: "zeitz" } },
		{ params: { city: "emden" } },
		{ params: { city: "neu-isenburg" } },
		{ params: { city: "arnsberg" } },
		{ params: { city: "espelkamp" } },
		{ params: { city: "gronau" } },
		{ params: { city: "waghaeusel" } },
		{ params: { city: "rinteln" } },
		{ params: { city: "nordhorn" } },
		{ params: { city: "hamburg-hafencity" } },
		{ params: { city: "cottbus" } },
		{ params: { city: "starnberg" } },
		{ params: { city: "eisenach" } },
		{ params: { city: "koeln" } },
		{ params: { city: "lohmar" } },
		{ params: { city: "herzogenrath" } },
		{ params: { city: "germersheim" } },
		{ params: { city: "wegberg" } },
		{ params: { city: "landau-in-der-pfalz" } },
		{ params: { city: "gersthofen" } },
		{ params: { city: "zirndorf" } },
		{ params: { city: "aachen" } },
		{ params: { city: "frankfurt-sachsenhausen" } },
		{ params: { city: "stade" } },
		{ params: { city: "bad-schwartau" } },
		{ params: { city: "kirchheim-unter-teck" } },
		{ params: { city: "radevormwald" } },
		{ params: { city: "norden" } },
		{ params: { city: "bad-kissingen" } },
		{ params: { city: "wetter-(ruhr)" } },
		{ params: { city: "dormagen" } },
		{ params: { city: "friedrichsdorf" } },
		{ params: { city: "weimar" } },
		{ params: { city: "guestrow" } },
		{ params: { city: "bietigheim-bissingen" } },
		{ params: { city: "warendorf" } },
		{ params: { city: "filderstadt" } },
		{ params: { city: "luedinghausen" } },
		{ params: { city: "grimma" } },
		{ params: { city: "herrenberg" } },
		{ params: { city: "fuerstenwalde" } },
		{ params: { city: "hanau" } },
		{ params: { city: "vaterstetten" } },
		{ params: { city: "griesheim" } },
		{ params: { city: "delmenhorst" } },
		{ params: { city: "herzogenaurach" } },
		{ params: { city: "bielefeld" } },
		{ params: { city: "rathenow" } },
		{ params: { city: "hemer" } },
		{ params: { city: "essen" } },
		{ params: { city: "seligenstadt" } },
		{ params: { city: "coburg" } },
		{ params: { city: "straubing" } },
		{ params: { city: "borken" } },
		{ params: { city: "wernigerode" } },
		{ params: { city: "lennestadt" } },
		{ params: { city: "graefelfing" } },
		{ params: { city: "iserlohn" } },
		{ params: { city: "koenigstein-im-taunus" } },
		{ params: { city: "westoverledingen" } },
		{ params: { city: "halle-(saale)" } },
		{ params: { city: "lueneburg" } },
		{ params: { city: "erlangen" } },
		{ params: { city: "limburg-an-der-lahn" } },
		{ params: { city: "osnabrueck" } },
		{ params: { city: "saarlouis" } },
		{ params: { city: "kamp-lintfort" } },
		{ params: { city: "weingarten" } },
		{ params: { city: "lohne-(oldenburg)" } },
		{ params: { city: "winsen-(luhe)" } },
		{ params: { city: "schwetzingen" } },
		{ params: { city: "spremberg" } },
		{ params: { city: "biberach-an-der-riss" } },
		{ params: { city: "korschenbroich" } },
		{ params: { city: "burgwedel" } },
		{ params: { city: "wiehl" } },
		{ params: { city: "osterode-am-harz" } },
		{ params: { city: "toenisvorst" } },
		{ params: { city: "steinfurt" } },
		{ params: { city: "rosenheim" } },
		{ params: { city: "meppen" } },
		{ params: { city: "schoenebeck" } },
		{ params: { city: "quedlinburg" } },
		{ params: { city: "zittau" } },
		{ params: { city: "wesseling" } },
		{ params: { city: "soest" } },
		{ params: { city: "fuerstenfeldbruck" } },
		{ params: { city: "ansbach" } },
		{ params: { city: "herdecke" } },
		{ params: { city: "westerstede" } },
		{ params: { city: "rastatt" } },
		{ params: { city: "bocholt" } },
		{ params: { city: "tuebingen" } },
		{ params: { city: "bergkamen" } },
		{ params: { city: "gotha" } },
		{ params: { city: "luebeck" } },
		{ params: { city: "homburg" } },
		{ params: { city: "elsdorf" } },
		{ params: { city: "halle-(westf)" } },
		{ params: { city: "pfungstadt" } },
		{ params: { city: "hoexter" } },
		{ params: { city: "schifferstadt" } },
		{ params: { city: "ludwigsburg" } },
		{ params: { city: "hilden" } },
		{ params: { city: "alsdorf" } },
		{ params: { city: "ditzingen" } },
		{ params: { city: "bergheim" } },
		{ params: { city: "markkleeberg" } },
		{ params: { city: "neuburg-an-der-donau" } },
		{ params: { city: "kerpen" } },
		{ params: { city: "herborn" } },
		{ params: { city: "euskirchen" } },
		{ params: { city: "neuss" } },
		{ params: { city: "erfurt" } },
		{ params: { city: "schwaebisch-gmuend" } },
		{ params: { city: "recklinghausen" } },
		{ params: { city: "jena" } },
		{ params: { city: "wismar" } },
		{ params: { city: "henstedt-ulzburg" } },
		{ params: { city: "stutensee" } },
		{ params: { city: "quickborn" } },
		{ params: { city: "saalfeld" } },
		{ params: { city: "fellbach" } },
		{ params: { city: "horb-am-neckar" } },
		{ params: { city: "viersen" } },
		{ params: { city: "taunusstein" } },
		{ params: { city: "heiligenhaus" } },
		{ params: { city: "ludwigshafen-am-rhein" } },
		{ params: { city: "baesweiler" } },
		{ params: { city: "halle-saale" } },
		{ params: { city: "nordhausen" } },
		{ params: { city: "butzbach" } },
		{ params: { city: "schwerte" } },
		{ params: { city: "bayreuth" } },
		{ params: { city: "verl" } },
		{ params: { city: "oehringen" } },
		{ params: { city: "haan" } },
		{ params: { city: "gaggenau" } },
		{ params: { city: "xanten" } },
		{ params: { city: "hof" } },
		{ params: { city: "aue-bad-schlema" } },
		{ params: { city: "witten" } },
		{ params: { city: "ronnenberg" } },
		{ params: { city: "zossen" } },
		{ params: { city: "hamminkeln" } },
		{ params: { city: "aschaffenburg" } },
		{ params: { city: "uebach-palenberg" } },
		{ params: { city: "werder" } },
		{ params: { city: "pirmasens" } },
		{ params: { city: "wandlitz" } },
		{ params: { city: "moers" } },
		{ params: { city: "warburg" } },
		{ params: { city: "kleinmachnow" } },
		{ params: { city: "halle" } },
		{ params: { city: "schwaebisch-hall" } },
		{ params: { city: "burgdorf" } },
		{ params: { city: "brilon" } },
		{ params: { city: "wallenhorst" } },
		{ params: { city: "koenigsbrunn" } },
		{ params: { city: "maintal" } },
		{ params: { city: "wermelskirchen" } },
		{ params: { city: "kamen" } },
		{ params: { city: "nagold" } },
		{ params: { city: "neuruppin" } },
		{ params: { city: "hueckelhoven" } },
		{ params: { city: "troisdorf" } },
		{ params: { city: "monheim-am-rhein" } },
		{ params: { city: "boeblingen" } },
		{ params: { city: "frechen" } },
		{ params: { city: "germering" } },
		{ params: { city: "neunkirchen" } },
		{ params: { city: "greifswald" } },
		{ params: { city: "traunstein" } },
		{ params: { city: "herford" } },
		{ params: { city: "kempten-(allgaeu)" } },
		{ params: { city: "bochum" } },
		{ params: { city: "stadthagen" } },
		{ params: { city: "bingen-am-rhein" } },
		{ params: { city: "laatzen" } },
		{ params: { city: "ach" } },
		{ params: { city: "glauchau" } },
		{ params: { city: "bergisch-gladbach" } },
		{ params: { city: "gladbeck" } },
		{ params: { city: "marl" } },
		{ params: { city: "muelheim-an-der-ruhr" } },
		{ params: { city: "cuxhaven" } },
		{ params: { city: "arnstadt" } },
		{ params: { city: "wertheim" } },
		{ params: { city: "wetter-ruhr" } },
	];

	return {
		paths,
		fallback: false, // Wenn die Stadt nicht auf der Liste ist, wird 404 angezeigt
	};
}

export async function getStaticProps({ params }) {
	const { city } = params;

	return {
		props: {
			city,
		},
	};
}

export default Webentwicklung;
